### PR TITLE
Cutting content to get to 4000 words (or less!)

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
@jtheinen and @brocksam, how would you all like to manage my changes?

There are going to be some drastic cuts and rewordings. Either I can just have at it and you all merge this PR in whole. Or I can work in more section by section basis. If you don't mind me making major edits, I can just run through the whole paper and we just accept it. That would be easiest. But if you want to review my work, then I can make it reviewable.

**Comment by jtheinen** [comment]
I don't mind you making major edits, If you prefer to run through the whole paper that is fine by me. I can review the whole thing, or I can review the pull request as you work on it. 

PS I just marked the pull request ready for review but was not intending on doing so, I don't know how to undo it:)

**Comment by brocksam** [comment]
I'm happy with major changes too.

> PS I just marked the pull request ready for review but was not intending on doing so, I don't know how to undo it:)

Does this mean this needs converting back to draft?

**Comment by moorepants** [comment]
Ok. I'll take a full pass on the paper. I'll see if I can get through it this week.

**Comment by brocksam** [comment]
Jan and I are meeting tomorrow. We'll update afterwards.

**Comment by moorepants** [comment]
Current texcount output:

```
$ texcount ollie-optimization.tex 
File: ollie-optimization.tex
Encoding: utf8
Words in text: 4624
Words in headers: 43
Words outside text (captions, etc.): 449
Number of headers: 17
Number of floats/tables/figures: 10
Number of math inlines: 126
Number of math displayed: 55
Subcounts:
  text+headers+captions (#headers/#floats/#inlines/#displayed)
  61+7+0 (1/0/0/0) _top_
  451+1+182 (1/1/13/0) Section: Introduction}\label{s_intro
  139+2+2 (1/1/0/0) Subsection: Skateboard Terminology
  368+4+40 (1/1/5/0) Subsection: Mechanics of the ollie} \label{ss_mechanics
  65+1+0 (1/0/0/0) Section: Method
  242+3+0 (1/0/1/0) Subsection: Optimal Control Problem
  161+1+79 (1/3/0/0) Subsection: Parameterization}\label{s_paropt
  151+2+0 (1/0/11/5) Subsection: General formulation
  205+3+0 (1/0/4/1) Subsection: Phases and Objective} \label{s_phases
  497+8+86 (2/3/20/14) Subsection: System Dynamics}\label{s_systemdynamics
  940+1+60 (1/1/22/10) Subsection: Constraints
  595+1+0 (1/0/22/6) Subsection: Friction
  519+2+0 (1/0/18/11) Subsection: Endpoint constraints} \label{p_endpoints
  59+1+0 (1/0/2/0) Subsection: Settings}\label{s_settings
  171+1+0 (1/0/8/8) Subsection: Summary}\label{s_summary
  0+5+0 (1/0/0/0) Section: Appendix: Equation of Motion Derivation
```

Let's merge this so we can more fluidly work on it.

**Comment by brocksam** [comment]
Once "ready for review", do you want this reviewed? Or shall we just merge so that others can make targeted edits as the review? I vote the latter.

**Comment by moorepants** [comment]
Let's just merge we have to edit the paper in the end, so it will be "reviewed".

**Comment by moorepants** [comment]
Merging.

**Pull request merged**
